# Generated by Django 5.0.2 on 2025-06-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='정당명', max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='정당 로고 이미지 URL', null=True)),
                ('slogan', models.CharField(blank=True, help_text='정당 슬로건', max_length=255)),
                ('description', models.TextField(blank=True, help_text='정당 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '정당',
                'verbose_name_plural': '정당 목록',
                'ordering': ['name'],
            },
        ),
    ]
