# Generated by Django 5.0.2 on 2025-06-03 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='의안 ID'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_nm',
            field=models.CharField(help_text='의안명', max_length=500, verbose_name='의안명'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='link_url',
            field=models.URLField(help_text='의안 상세 URL', verbose_name='의안 상세 URL'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.session', verbose_name='관련 회의'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.TextField(blank=True, help_text='정당 설명', verbose_name='정당 설명'),
        ),
        migrations.AlterField(
            model_name='party',
            name='logo_url',
            field=models.URLField(blank=True, help_text='정당 로고 이미지 URL', null=True, verbose_name='정당 로고 URL'),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(help_text='정당명', max_length=100, unique=True, verbose_name='정당명'),
        ),
        migrations.AlterField(
            model_name='party',
            name='slogan',
            field=models.CharField(blank=True, help_text='정당 슬로건', max_length=255, verbose_name='정당 슬로건'),
        ),
        migrations.AlterField(
            model_name='party',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='session',
            name='bg_ptm',
            field=models.TimeField(help_text='시작시간', verbose_name='시작시간'),
        ),
        migrations.AlterField(
            model_name='session',
            name='cmit_nm',
            field=models.CharField(help_text='위원회명', max_length=100, verbose_name='위원회명'),
        ),
        migrations.AlterField(
            model_name='session',
            name='conf_dt',
            field=models.DateField(help_text='회의일자', verbose_name='회의일자'),
        ),
        migrations.AlterField(
            model_name='session',
            name='conf_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='회의 ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='conf_knd',
            field=models.CharField(help_text='회의종류', max_length=100, verbose_name='회의종류'),
        ),
        migrations.AlterField(
            model_name='session',
            name='conf_plc',
            field=models.CharField(blank=True, help_text='회의장소', max_length=200, verbose_name='회의장소'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='session',
            name='dgr',
            field=models.CharField(help_text='차수', max_length=20, verbose_name='차수'),
        ),
        migrations.AlterField(
            model_name='session',
            name='down_url',
            field=models.URLField(help_text='PDF 다운로드 URL', verbose_name='PDF 다운로드 URL'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ed_ptm',
            field=models.TimeField(help_text='종료시간', verbose_name='종료시간'),
        ),
        migrations.AlterField(
            model_name='session',
            name='era_co',
            field=models.CharField(help_text='대수', max_length=20, verbose_name='대수'),
        ),
        migrations.AlterField(
            model_name='session',
            name='sess',
            field=models.CharField(help_text='회기', max_length=20, verbose_name='회기'),
        ),
        migrations.AlterField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='blng_cmit_nm',
            field=models.CharField(blank=True, help_text='소속위원회명', max_length=200, verbose_name='소속위원회명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='cmit_nm',
            field=models.CharField(blank=True, help_text='대표위원회명', max_length=100, verbose_name='대표위원회명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='elecd_div_nm',
            field=models.CharField(help_text='선거구구분명', max_length=100, verbose_name='선거구 구분명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='elecd_nm',
            field=models.CharField(help_text='선거구명', max_length=200, verbose_name='선거구명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='gtelt_eraco',
            field=models.CharField(help_text='당선대수', max_length=100, verbose_name='당선대수'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='naas_cd',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='국회의원 코드'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='naas_ch_nm',
            field=models.CharField(blank=True, help_text='국회의원한자명', max_length=100, verbose_name='국회의원 한자명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='naas_nm',
            field=models.CharField(help_text='국회의원명', max_length=100, verbose_name='국회의원명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='naas_pic',
            field=models.URLField(blank=True, help_text='국회의원사진 URL', verbose_name='국회의원 사진 URL'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='ntr_div',
            field=models.CharField(help_text='성별', max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='plpt_nm',
            field=models.CharField(help_text='정당명', max_length=100, verbose_name='정당명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='rlct_div_nm',
            field=models.CharField(help_text='재선구분명', max_length=50, verbose_name='재선구분명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='api.bill', verbose_name='관련 의안'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='sentiment_reason',
            field=models.TextField(help_text='감성 분석 근거', verbose_name='감성 분석 근거'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='sentiment_score',
            field=models.FloatField(help_text='감성 점수 (-1 ~ 1)', verbose_name='감성 점수'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='api.session', verbose_name='관련 회의'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='api.speaker', verbose_name='발언자'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='text',
            field=models.TextField(help_text='발언 내용', verbose_name='발언 내용'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
