# Generated by Django 5.0.2 on 2025-06-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bill_bill_id_alter_bill_bill_nm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ed_ptm',
            field=models.TimeField(blank=True, help_text='종료시간', null=True, verbose_name='종료시간'),
        ),
    ]
