# Generated by Django 5.0.2 on 2025-06-05 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_session_ed_ptm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='카테고리명', max_length=100, unique=True, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, help_text='카테고리 설명', verbose_name='카테고리 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='statement',
            name='category_analysis',
            field=models.TextField(blank=True, help_text='카테고리 분석 결과', verbose_name='카테고리 분석 결과'),
        ),
        migrations.AddField(
            model_name='statement',
            name='policy_keywords',
            field=models.TextField(blank=True, help_text='정책 키워드', verbose_name='정책 키워드'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='하위카테고리명', max_length=100, verbose_name='하위카테고리명')),
                ('description', models.TextField(blank=True, help_text='하위카테고리 설명', verbose_name='하위카테고리 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '하위카테고리',
                'verbose_name_plural': '하위카테고리 목록',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StatementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0, help_text='분류 신뢰도 (0-1)', verbose_name='분류 신뢰도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='카테고리')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.statement', verbose_name='발언')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subcategory', verbose_name='하위카테고리')),
            ],
            options={
                'verbose_name': '발언 카테고리',
                'verbose_name_plural': '발언 카테고리 목록',
                'ordering': ['-confidence_score'],
                'unique_together': {('statement', 'category')},
            },
        ),
    ]
