# Generated by Django 5.0.2 on 2025-06-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_statement_category_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='bg_ptm',
            field=models.TimeField(blank=True, help_text='시작시간', null=True, verbose_name='시작시간'),
        ),
    ]
