# Generated by Django 5.0.2 on 2025-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_session_bg_ptm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='blng_cmit_nm',
            field=models.CharField(blank=True, help_text='소속위원회명', max_length=200, null=True, verbose_name='소속위원회명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='cmit_nm',
            field=models.CharField(blank=True, help_text='대표위원회명', max_length=100, null=True, verbose_name='대표위원회명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='elecd_div_nm',
            field=models.CharField(blank=True, help_text='선거구구분명', max_length=100, null=True, verbose_name='선거구 구분명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='elecd_nm',
            field=models.CharField(blank=True, help_text='선거구명', max_length=200, null=True, verbose_name='선거구명'),
        ),
    ]
