# Generated by Django 5.0.2 on 2025-06-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_speaker_blng_cmit_nm_alter_speaker_cmit_nm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='blng_cmit_nm',
            field=models.CharField(blank=True, help_text='소속위원회명', max_length=500, null=True, verbose_name='소속위원회명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='cmit_nm',
            field=models.CharField(blank=True, help_text='대표위원회명', max_length=300, null=True, verbose_name='대표위원회명'),
        ),
    ]
