# Generated by Django 5.0.2 on 2025-06-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_speaker_blng_cmit_nm_alter_speaker_cmit_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='blng_cmit_nm',
            field=models.TextField(blank=True, help_text='소속위원회명', null=True, verbose_name='소속위원회명'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='cmit_nm',
            field=models.TextField(blank=True, help_text='대표위원회명', null=True, verbose_name='대표위원회명'),
        ),
    ]
