# Generated by Django 5.0.2 on 2025-06-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_speaker_blng_cmit_nm_alter_speaker_cmit_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='current_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_members', to='api.party', verbose_name='현재 정당'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='plpt_nm',
            field=models.CharField(help_text='정당명 (전체 이력)', max_length=500, verbose_name='정당명'),
        ),
        migrations.CreateModel(
            name='SpeakerPartyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='정당 이력 순서 (0부터 시작)', verbose_name='순서')),
                ('is_current', models.BooleanField(default=False, help_text='현재 소속 정당 여부', verbose_name='현재 정당')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.party', verbose_name='정당')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.speaker', verbose_name='국회의원')),
            ],
            options={
                'verbose_name': '국회의원 정당 이력',
                'verbose_name_plural': '국회의원 정당 이력',
                'ordering': ['speaker', 'order'],
                'unique_together': {('speaker', 'party', 'order')},
            },
        ),
        migrations.AddField(
            model_name='speaker',
            name='party_history',
            field=models.ManyToManyField(related_name='historical_members', through='api.SpeakerPartyHistory', to='api.party', verbose_name='정당 이력'),
        ),
    ]
