# Generated by Django 5.0.2 on 2025-06-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_speaker_current_party_alter_speaker_plpt_nm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='assembly_era',
            field=models.PositiveIntegerField(default=22, help_text='국회 대수 (예: 22)', verbose_name='국회 대수'),
        ),
    ]
