# Generated by Django 5.0.2 on 2025-06-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_party_assembly_era'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, help_text='회의 제목', max_length=500, verbose_name='회의 제목'),
        ),
    ]
