# Generated by Django 5.0.2 on 2025-06-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_session_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='text_hash',
            field=models.CharField(blank=True, help_text='텍스트 해시', max_length=64, verbose_name='텍스트 해시'),
        ),
    ]
