# Generated by Django 5.0.2 on 2025-06-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_statement_text_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_result', models.CharField(choices=[('찬성', '찬성'), ('반대', '반대'), ('기권', '기권'), ('불참', '불참'), ('무효', '무효')], max_length=10, verbose_name='투표 결과')),
                ('vote_date', models.DateTimeField(verbose_name='투표 일시')),
                ('sentiment_score', models.FloatField(help_text='투표 감성 점수 (-1 ~ 1)', verbose_name='투표 감성 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_records', to='api.bill', verbose_name='관련 의안')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting_records', to='api.session', verbose_name='관련 회의')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_records', to='api.speaker', verbose_name='투표자')),
            ],
            options={
                'verbose_name': '투표 기록',
                'verbose_name_plural': '투표 기록',
                'ordering': ['-vote_date'],
                'unique_together': {('bill', 'speaker')},
            },
        ),
    ]
