# Generated by Django 5.0.2 on 2025-06-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_votingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='bill_relevance_score',
            field=models.FloatField(blank=True, help_text='의안 관련성 점수 (0-1)', null=True, verbose_name='의안 관련성 점수'),
        ),
        migrations.AddField(
            model_name='statement',
            name='bill_specific_keywords_json',
            field=models.TextField(blank=True, help_text='의안 관련 키워드 JSON', verbose_name='의안 관련 키워드'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='sentiment_reason',
            field=models.TextField(blank=True, help_text='감성 분석 근거', verbose_name='감성 분석 근거'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='감성 점수 (-1 ~ 1)', null=True, verbose_name='감성 점수'),
        ),
        migrations.AlterField(
            model_name='votingrecord',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='투표 감성 점수 (-1 ~ 1)', verbose_name='투표 감성 점수'),
        ),
        migrations.AlterField(
            model_name='votingrecord',
            name='vote_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='투표 일시'),
        ),
    ]
