# Generated by Django 5.0.2 on 2025-06-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_bill_policy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(blank=True, help_text='의안번호', max_length=100, null=True, verbose_name='의안번호'),
        ),
    ]
