# Generated by Django 5.0.2 on 2025-06-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_bill_bill_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '정책 대범주', 'verbose_name_plural': '정책 대범주 목록'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category__name', 'name'], 'verbose_name': '정책 소범주', 'verbose_name_plural': '정책 소범주 목록'},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_specific_keywords_found',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='bill_specific_keywords_json',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='category_analysis',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='policy_keywords',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_specific_keywords',
            field=models.JSONField(blank=True, default=list, help_text='의안별 특화 키워드 목록', verbose_name='의안별 특화 키워드'),
        ),
        migrations.AddField(
            model_name='bill',
            name='category_analysis',
            field=models.TextField(blank=True, help_text='카테고리 분석 결과', verbose_name='카테고리 분석 결과'),
        ),
        migrations.AddField(
            model_name='bill',
            name='llm_analysis_version',
            field=models.CharField(blank=True, help_text='LLM 분석 버전', max_length=20, verbose_name='분석 버전'),
        ),
        migrations.AddField(
            model_name='bill',
            name='llm_confidence_score',
            field=models.FloatField(blank=True, help_text='LLM 분석 신뢰도 (0-1)', null=True, verbose_name='분석 신뢰도'),
        ),
        migrations.AddField(
            model_name='bill',
            name='policy_impact_score',
            field=models.FloatField(blank=True, help_text='정책 영향도 점수 (0-10)', null=True, verbose_name='정책 영향도'),
        ),
        migrations.AddField(
            model_name='bill',
            name='policy_keywords',
            field=models.TextField(blank=True, help_text='정책 키워드 (쉼표 구분)', verbose_name='정책 키워드'),
        ),
        migrations.AddField(
            model_name='bill',
            name='policy_subcategories',
            field=models.JSONField(blank=True, default=list, help_text='LLM 분석된 정책 소범주 목록', verbose_name='정책 소범주'),
        ),
        migrations.AddField(
            model_name='category',
            name='policy_area_code',
            field=models.CharField(blank=True, help_text='정책영역 코드', max_length=20, verbose_name='정책영역 코드'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='implementation_approach',
            field=models.TextField(blank=True, help_text='구체적 실행 방안', verbose_name='실행 방안'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='policy_stance',
            field=models.CharField(blank=True, help_text='정책 성향 (진보/보수/중도)', max_length=50, verbose_name='정책 성향'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='key_policy_phrases',
            field=models.JSONField(blank=True, default=list, help_text='핵심 정책 키워드 목록', verbose_name='핵심 정책 키워드'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='policy_categories',
            field=models.JSONField(blank=True, default=list, help_text='LLM 분석된 정책 대범주 목록', verbose_name='정책 카테고리'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='proposer',
            field=models.CharField(blank=True, default='정보 없음', help_text='제안자/제안위원회', max_length=200, null=True, verbose_name='제안자'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='대범주명 (예: 경제정책, 사회정책)', max_length=100, unique=True, verbose_name='대범주명'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category', verbose_name='상위 대범주'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, help_text='소범주 정책 설명', verbose_name='소범주 설명'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='소범주명 (예: 확장재정, 긴축재정)', max_length=100, verbose_name='소범주명'),
        ),
        migrations.CreateModel(
            name='BillCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0, help_text='LLM 분류 신뢰도 (0-1)', verbose_name='분류 신뢰도')),
                ('is_primary', models.BooleanField(default=False, help_text='주요 범주 여부', verbose_name='주요 범주')),
                ('analysis_method', models.CharField(default='llm_analysis', help_text='분석 방법 (llm_analysis, manual, etc.)', max_length=50, verbose_name='분석 방법')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='api.bill', verbose_name='의안')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_mappings', to='api.category', verbose_name='정책 대범주')),
            ],
            options={
                'verbose_name': '의안-대범주 매핑',
                'verbose_name_plural': '의안-대범주 매핑 목록',
                'ordering': ['-confidence_score', '-is_primary'],
                'unique_together': {('bill', 'category')},
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='primary_categories',
            field=models.ManyToManyField(related_name='primary_bills', through='api.BillCategoryMapping', to='api.category', verbose_name='주요 정책 범주'),
        ),
        migrations.CreateModel(
            name='BillSubcategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0, help_text='관련성 점수 (0-1)', verbose_name='관련성 점수')),
                ('supporting_evidence', models.TextField(blank=True, help_text='분류 근거 텍스트', verbose_name='분류 근거')),
                ('extracted_keywords', models.JSONField(blank=True, default=list, help_text='추출된 관련 키워드', verbose_name='관련 키워드')),
                ('policy_position', models.CharField(blank=True, choices=[('support', '지지'), ('oppose', '반대'), ('neutral', '중립'), ('unknown', '불명')], help_text='해당 정책에 대한 입장', max_length=20, verbose_name='정책 입장')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_mappings', to='api.bill', verbose_name='의안')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_subcategories', to='api.subcategory', verbose_name='정책 소범주')),
            ],
            options={
                'verbose_name': '의안-소범주 매핑',
                'verbose_name_plural': '의안-소범주 매핑 목록',
                'ordering': ['-relevance_score'],
                'unique_together': {('bill', 'subcategory')},
            },
        ),
    ]
